### ISSUE TITLE
url's aren't loaded from an akitarc

### ISSUE THREAD

**Issue by robb-j** [robb-j/akita#1]
```
~/Sites/me/akita master → cat .akitarc.yml 
url: ws://localhost:3000

messages:
  helloWorld: A really long string payload
  
  customData:
    name: Geoff
    age: 42
```

```
~/Sites/me/akita master → akita
𐄂 No url provided
```
